#!/bin/sh

OLD_WINDOW=`xdotool getactivewindow`
WINDOW=`xdotool search "$1" 2> /dev/null | head -1`
xdotool windowfocus $WINDOW
xdotool windowraise $WINDOW

xdotool key Up
xdotool key Return

xdotool windowfocus $OLD_WINDOW
xdotool windowraise $OLD_WINDOW
